[package]
name = "hos_screensaver"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.27"
rand = "0.8"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader"] }
